apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: zoofpm
  name: zoofpm
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zoofpm
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: zoofpm
    spec:
      containers:
        - args:
            - /startUp.sh
          env:
            - name: ZOO_RABBITMQ_HOST
              value: rabbitmq
          image: djayzen/zookernel:latest
          name: zoofpm
          resources: {}
          volumeMounts:
            - mountPath: /usr/lib/cgi-bin/main.cfg
              name: zoofpm-claim0
            - mountPath: /usr/lib/cgi-bin/oas.cfg
              name: zoofpm-claim1
            - mountPath: /tmp/zTmp
              name: zoofpm-claim2
            - mountPath: /usr/com/zoo-project
              name: zoofpm-claim3
            - mountPath: /usr/lib/cgi-bin/ws2022
              name: zoofpm-claim4
            - mountPath: /var/www/html/zoows-2022/
              name: zoofpm-claim5
            - mountPath: /var/data
              name: zoofpm-claim6
      restartPolicy: Always
      volumes:
        - name: zoofpm-claim0
          persistentVolumeClaim:
            claimName: zoofpm-claim0
        - name: zoofpm-claim1
          persistentVolumeClaim:
            claimName: zoofpm-claim1
        - name: zoofpm-claim2
          persistentVolumeClaim:
            claimName: zoofpm-claim2
        - name: zoofpm-claim3
          persistentVolumeClaim:
            claimName: zoofpm-claim3
        - name: zoofpm-claim4
          persistentVolumeClaim:
            claimName: zoofpm-claim4
        - name: zoofpm-claim5
          persistentVolumeClaim:
            claimName: zoofpm-claim5
        - name: zoofpm-claim6
          persistentVolumeClaim:
            claimName: zoofpm-claim6
status: {}
